FROM centos:7
MAINTAINER Lei Wei <leiwei2094@gmail.com>
ENV REFRESHED_AT 2017-04-17
RUN yum install -y java-1.8.0-openjdk.x86_64
RUN yum install -y curl
RUN yum install -y lsof
#COPY app.sh.sample /opt/app.sh.sample
#RUN chmod +x /opt/app.sh.sample
#ENTRYPOINT ["/opt/app.sh.sample"]